FROM sonarqube:lts

# качаем два плагина, кладем в каталог /opt/sonarqube/extensions/downloads
RUN mkdir /opt/sonarqube/extensions/downloads/
RUN curl -L  https://github.com/1c-syntax/sonar-bsl-plugin-community/releases/download/v1.5.0/sonar-communitybsl-plugin-1.5.0.jar --output /opt/sonarqube/extensions/downloads/sonar-communitybsl-plugin-1.5.0.jar
RUN curl -L  https://github.com/silverbulleters/sonar-l10n-ru/releases/download/v1.9/sonar-l10n-ru-plugin-1.9.jar --output /opt/sonarqube/extensions/downloads/sonar-l10n-ru-plugin-1.9.jar 
